POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT FOREIGN KEY, hinta INTEGER);",
  "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);"
  ]
}

###

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": "test"
}

###

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": [
  "CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER, lkm INTEGER);",
  "INSERT INTO Tuotteet (nimi,hinta,lkm) VALUES ('retiisi', 7, 20);",
  "INSERT INTO Tuotteet (nimi,hinta,lkm) VALUES ('porkkana', 5, 40);",
  "INSERT INTO Tuotteet (nimi,hinta,lkm) VALUES ('nauris', 4, 40);",
  "INSERT INTO Tuotteet (nimi,hinta,lkm) VALUES ('lanttu', 8, 20);",
  "INSERT INTO Tuotteet (nimi,hinta,lkm) VALUES ('selleri', 4, 30);",
  "INSERT INTO Tuotteet (nimi,hinta,lkm) VALUES ('selleri', 4, 70);",
  "INSERT INTO Tuotteet (nimi,hinta,lkm) VALUES ('maito', 6, 70);",
  "INSERT INTO Tuotteet (nimi,hinta, lkm) VALUES ('olut',4, 50);",
  "INSERT INTO Tuotteet (nimi,hinta, lkm) VALUES ('olut',4, 70);",
  "INSERT INTO Tuotteet (nimi,hinta, lkm) VALUES ('olut',5, 40);",
  "INSERT INTO Tuotteet (nimi,hinta, lkm) VALUES ('olut',5, 40);",
  "SELECT nimi, hinta, SUM(lkm), COUNT(*) FROM Tuotteet GROUP BY nimi, hinta ORDER BY hinta DESC, nimi;"
  ]
}

### Testing invalid query:

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet    (id INTEGER PRIMARY KEY,    nimi TEXT,    hinta INTEGER);",
  "SELECT * FROM Tuotteet",
  "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);"
  ]
}
