### Valid queries

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "SELECT * FROM Tuotteet;"
  ]
}

### Valid query for inserting several rows

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('omena', 5);",
    "SELECT * FROM Tuotteet;"
  ]
}

### Valid queries demonstrating keyword case-insensitivity

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CReAtE TAbLE Tuotteet (id INTEgER PRImARY KeY, nimi TExT, hinta INTeGER);",
    "INSeRT InTO Tuotteet (nimi, hinta) VALuES ('retiisi', 7);",
    "SELeCT * FrOm Tuotteet;"
  ]
}

### Unrecognisable first query

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "SELECT * FROM Tuotteet;"
  ]
}

### Invalid CREATE TABLE -query

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TX, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "SELECT * FROM Tuotteet;"
  ]
}

### Invalid CREATE TABLE -query (duplicate columns)

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, nimi INTEGER, id TEXT);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "SELECT * FROM Tuotteet;"
  ]
}

### Invalid CREATE TABLE -query (wrong data type for column)

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES (123, 'string');",
    "SELECT * FROM Tuotteet;"
  ]
}

### Invalid SELECT * -query

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "SELECT * FROM Tuotteet"
  ]
}

### Invalid INSERT INTO -query

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7));",
    "SELECT * FROM Tuotteet;"
  ]
}

### For testing SELECT * ... WHERE ..
POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
  "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
  "INSERT INTO Tuotteet (nimi, hinta) VALUES ('omena', 5);",
    "SELECT * FROM Tuotteet WHERE hinta>5;",
    "SELECT * FROM Tuotteet WHERE nimi='omena';"
  ]
}

### SELECT column_1, column_2 FROM ... WHERE ...

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": [
  "CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
  "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 4);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('porkkana',5);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('nauris',4);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('lanttu',4);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('selleri',4);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('selleri',1);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('selleri',6);",
  "SELECT nimi FROM Tuotteet WHERE hinta=4;"
  ]
}

### SELECT column_1, column_2 FROM ... WHERE ... ORDER BY

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": [
  "CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
  "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 4);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('porkkana',5);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('nauris',4);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('lanttu',4);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('selleri',4);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('selleri',1);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('selleri',6);",
  "SELECT nimi FROM Tuotteet WHERE hinta=4 ORDER BY nimi DESC;"
  ]
}

### UPDATE ... SET ... ;

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": [
    "CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('omena', 5);",
    "UPDATE Tuotteet SET hinta=10;",
    "SELECT * FROM Tuotteet;"
  ]
}

### UPDATE ... SET ... WHERE ...;

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": [
    "CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('omena', 5);",
    "UPDATE Tuotteet SET nimi='ananas' WHERE nimi='retiisi';",
    "SELECT * FROM Tuotteet;"
  ]
}

### UPDATE ... SET ... WHERE ...; with wrong datatype as value

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": [
    "CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('omena', 5);",
    "UPDATE Tuotteet SET nimi=6 WHERE nimi='retiisi';",
    "SELECT * FROM Tuotteet;"
  ]
}

### UPDATE ... SET ... WHERE ... AND;

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": [
    "CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('omena', 5);",
    "UPDATE Tuotteet SET nimi='ananas' WHERE nimi='retiisi' AND hinta=7;",
    "SELECT * FROM Tuotteet;"
  ]
}

### UPDATE ... SET ... WHERE ... OR;

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": [
    "CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('omena', 5);",
    "UPDATE Tuotteet SET nimi='ananas' WHERE nimi='retiisi' OR hinta=5;",
    "SELECT * FROM Tuotteet;"
  ]
}

### DELETE testing

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": [
  "CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
  "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 4);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('porkkana',5);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('nauris',4);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('lanttu',4);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('selleri',4);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('selleri',1);",
  "INSERT INTO Tuotteet (nimi,hinta) VALUES ('selleri',6);",
  "DELETE FROM Tuotteet WHERE hinta=4;",
  "SELECT * FROM Tuotteet ORDER BY hinta;"
  ]
}

### SELECT DISTINCT ...

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": [
    "CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('omena', 7);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('omena', 7);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('olut', 7);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('olut', 7);",
    "SELECT DISTINCT nimi, hinta FROM Tuotteet WHERE hinta=7 ORDER BY nimi ASC;"
  ]
}