# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
# Orchestrate or schedule a set of jobs
jobs:
    build:
        docker:
            - image: 'circleci/node:latest'
        steps:
            - checkout
            - run: npm install
            - run: npm run lint
            - run: npm run test
            - run: npm run testcoverage
            - run: echo 'hello world'

workflows:
    build_and_test:
        jobs:
            - build
