### Failing queries

### #1
POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
  "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7)",
  "SELECT * FROM Tuotteet;"
  ]
}
### #2
POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
  "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7)",
  "SELECT * FROM Tuotteet;"
  ]
}

### #3
POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
  "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7",
  "SELECT * FROM Tuotteet;"
  ]
}

### #4
POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
  "INSERT INTO Tuotteet (nimi, hinta); VALUES ('retiisi', 7);",
  "SELECT * FROM Tuotteet;"
  ]
}

### Valid queries

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "SELECT * FROM Tuotteet;"
  ]
}

### Valid query for inserting several rows

POST http://localhost:3001/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('omena', 5);",
    "SELECT * FROM Tuotteet;"
  ]
}