### Valid queries

POST https://hy-sql.herokuapp.com/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "SELECT * FROM Tuotteet;"
  ]
}

### Valid queries demonstrating keyword case-insensitivity

POST https://hy-sql.herokuapp.com/api/query
Content-Type: application/json

{
  "commandArray": ["CReAtE TAbLE Tuotteet (id INTEgER PRImARY KeY, nimi TExT, hinta INTeGER);",
    "INSeRT InTO Tuotteet (nimi, hinta) VALuES ('retiisi', 7);",
    "SELeCT * FrOm Tuotteet;"
  ]
}

### Unrecognisable first query

POST https://hy-sql.herokuapp.com/api/query
Content-Type: application/json

{
  "commandArray": ["TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "SELECT * FROM Tuotteet;"
  ]
}

### Invalid CREATE TABLE -query

POST https://hy-sql.herokuapp.com/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TX, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "SELECT * FROM Tuotteet;"
  ]
}

### Invalid SELECT * -query

POST https://hy-sql.herokuapp.com/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "SELECT * FROM Tuotteet"
  ]
}

### Invalid INSERT INTO -query

POST https://hy-sql.herokuapp.com/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
    "INSERT INTO Tuotteet nimi, hinta) VALUES ('retiisi', 7);",
    "SELECT * FROM Tuotteet;"
  ]
}

### For testing SELECT * ... WHERE ..
POST https://hy-sql.herokuapp.com/api/query
Content-Type: application/json

{
  "commandArray": ["CREATE TABLE Tuotteet (id INTEGER PRIMARY KEY, nimi TEXT, hinta INTEGER);",
  "INSERT INTO Tuotteet (nimi, hinta) VALUES ('retiisi', 7);",
    "SELECT * FROM Tuotteet WHERE hinta=7;",
    "SELECT * FROM Tuotteet WHERE nimi='retiisi';"
  ]
}
